from datetime import datetime

from facebook_scraper import get_posts
from exceptions import FacebookPostNotFoundError
from exchange_rate import ExchangeRate

SOURCE = 'IRemit Walk-in'
FEE = 4


def get_rate():
    '''
    Scrape from Facebook. Get rate from image's description.
    Image description could be auto-generated by Facebook.
    '''
    for post in get_posts('iremitsg', pages=20):
        # Sample: May be an image of text that says 'BEST RATES! Google Play SEND MONEY ONLINE TO THEPHILIPPINES
        # Use IREMITX 24/7 DOWNLOAD NOW! Pownbadenthe App Store or REMIT Cash using an DBS POSB ATM EXCHANGE RATE FOR TODAY Dec. 5, 2022
        # IREMITX 41.16 WALK-IN 41.10 DISCLAIMER...
        images_description = post['images_description']
        timestamp: datetime = post['time']

        if not images_description:
            continue

        description: str = images_description[0].lower()

        if 'exchange rate for today' in description:
            text_to_parse = description.split(
                'exchange rate for today', 1)[1]

            split = text_to_parse.split()
            i = 0
            length = len(split)
            while i < length:
                curr = split[i]
                if curr == 'walk-in' or curr == 'walkin' and i + 1 < length:
                    next_token = split[i + 1]
                    if (is_decimal(next_token)):
                        return ExchangeRate(effective_on=timestamp, source=SOURCE, rate=next_token, fee=FEE, updated_on=datetime.now())
                    break

                i += 1
    raise FacebookPostNotFoundError(
        'IRemit Walk-in rate from Facebook not found')


def is_decimal(string) -> bool:
    return string.replace('.', '', 1).isdigit()


def main():
    rate = get_rate()
    print(rate)


if __name__ == '__main__':
    main()
