from datetime import datetime
from decimal import Decimal

from facebook_scraper import get_posts
from exchange_rate import ExchangeRate

SOURCE = 'IRemit Walk-in'
FEE = 4


def get_rate():
    '''
    Scrape from Facebook. Get rate from image's description.
    Image description could be auto-generated by Facebook.
    '''
    for post in get_posts('iremitsg', pages=20):
        # Sample: May be an image of text that says 'BEST RATES! Google Play SEND MONEY ONLINE TO THEPHILIPPINES Use IREMITX 24/7 DOWNLOAD NOW! Pownbadenthe App Store or REMIT Cash using an DBS POSB ATM EXCHANGE RATE FOR TODAY Dec. 5, 2022 IREMITX 41.16 WALK-IN 41.10 DISCLAIMER Changes our exchange ates may be applied Immediately and without prior notice. STAY SAFE AND VIRUS-FREE! I-REMITTANCE SINGAPORE PTE LTD 304 Orchard Road #03-69 Lucky Plaza, Singapore 238863 REMIT SINGAPORE'
        images_description = post['images_description']
        timestamp: datetime = post['time']

        if not images_description:
            return None

        description: str = images_description[0].lower()

        if 'exchange rate for today' in description:
            text_to_parse = description.split(
                'exchange rate for today', 1)[1]

            split = text_to_parse.split()
            i = 0
            length = len(split)
            while i < length:
                curr = split[i]
                if curr == 'walk-in' or curr == 'walkin' and i + 1 < length:
                    next_token = split[i + 1]
                    if (is_decimal(next_token)):
                        rate = Decimal(next_token)
                        return ExchangeRate(timestamp, SOURCE, rate, FEE, datetime.now())
                    break

                i += 1
    return None


def is_decimal(string) -> bool:
    return string.replace('.', '', 1).isdigit()


def main():
    rate = get_rate()
    print(rate)


if __name__ == '__main__':
    main()
